### ISSUE TITLE
Can not add a user group in Contao

### ISSUE THREAD

**Issue by webwerkwien** [MetaModels/core#1340] opened 2019-10-09 13:07 UTC
While having no user group yet, it throws the following error if I am trying to add one:

Type error: Too few arguments to function tl_user_group::getModules(), 0 passed in /var/www/clients/client2/web748/web/contao/vendor/metamodels/core/src/CoreBundle/Contao/Hooks/FixupUserGroupModules.php on line 86 and exactly 1 expected

Using Contao 4.4.44, attribute_timestamp 2.1.0, bundle_start 2.1.2, contao-frontend-editing 2.1.0 and PHP 7.2.16. I do not use any other extensions.

**Comment by webwerkwien** [comment] 2019-10-10 08:14
Good morning, I deleted the extensions and was able to create new user groups. Afterwards I installed MetaModels Core 2.1.5, some filters, some attributes and the contao-frontend-editing. Again there is the error, when I try to add a new user group and when I try to edit an existing one.

**Comment by zonky2** [comment] 2019-10-10 08:38
I can check this next week...

**Comment by kampfq** [comment] 2019-10-18 13:03
i created a pull request for this, #1341

**Comment by discordier** [comment] 2019-10-18 22:07
Closing in favor of #1341

**Comment by zonky2** [comment] 2019-10-18 22:12
PR is not checked to me and I can't reproduce the error message in any project :(

**Comment by zonky2** [comment] 2019-10-18 22:19
checked :D

**Closed by zonky2** 2019-10-18 22:19 UTC
Labels: backend, bug, easy pick
