### ISSUE TITLE
Sorting in the backend is not working

### ISSUE THREAD

**Issue by cboelter** [MetaModels/core#776] opened 2015-03-11 10:36 UTC
I have configured a sorting in the backend configuration, but in the listview it is not applied. 
![bildschirmfoto 2015-03-11 um 11 33 27](https://cloud.githubusercontent.com/assets/550207/6594532/7779ec14-c7e2-11e4-8b6e-e1c06e333b16.png)
![bildschirmfoto-2015-03-11-um-11 34 21](https://cloud.githubusercontent.com/assets/550207/6594566/c0f7d5b8-c7e2-11e4-8584-fec3998d6120.gif)
As you can see it is currently sorted by the id and not by the startdate.

@discordier can you have a look on it, we need it for an project in pre live state :(

**Comment by discordier** [comment] 2015-03-12 12:46
Can you provide me with logins, xdebug etc? I could have a look.

**Comment by cboelter** [comment] 2015-03-12 13:39
@discordier You've got mail :)

**Comment by cboelter** [comment] 2015-03-16 09:23
@discordier any news?

**Comment by discordier** [comment] 2015-03-19 01:44
Still waiting for .htaccess login data...

**Comment by cboelter** [comment] 2015-03-19 01:50
I have sent it to you 4 minutes after I received the information from you :( ... 

No problem I have sent it again now. Please check your mails.

**Comment by cboelter** [comment] 2015-03-20 07:01
@discordier Did you received my email?

**Comment by discordier** [comment] 2015-03-20 18:42
Yeah, received it. In the original mail the credentials were merged into the "On XXX ... wrote" line of your reply and therefore I simply missed it. :(

My bad, working on it right now.

**Comment by discordier** [comment] 2015-03-20 18:59
Ok, I found the root cause.
The sorting is not being applied at all when no grouping is defined.
Interesting fact is, the grouping appears to be still applied when "do not group" is selected.

I have temporarily activated the grouping in your MetaModel and deactivated it later on for the other one again. Sorting still works as expected.

This is an issue in dc-general and one in MM core, which seems to ignore the fact that the grouping is disabled (wich is actually now active in your installation and provides a "workaround" based on the fact that this bug exists).

**Comment by cboelter** [comment] 2015-03-20 19:05
@discordier Thanks for having a look on it. What do you think about the costs for fixing it in MM and dc-general. If it is not too mich, I can sponsor it.

**Comment by discordier** [comment] 2015-03-20 19:17
The fix in MM is trivial as I simply have to add the checks if grouping is defined and ignore the settings for grouping then.

The sorting/grouping fix in dc-general will be definately more, hard to guess as I have not found out yet why the sorting is not applied there. Will have to dig into that one further but I suspect that it has to do with the changes from the rework-sorting applied several weeks ago.

**Comment by Aybee** [comment] 2015-05-12 21:41
Sorting will not work even if grouping is selected. It only seams to work as it gets sorted ascending.

Create **one sorting asc** and **one sorting desc**. Try to switch between them with the select. Nothing happens.

Tested on:
- Contao 3.4.5
- three minor extensions (deactivated)
- Nightly from 12.05.2015
- metamodels/core                                  dev-tng @ 1f4fd6        2015-05-05 21:56:41

Reproduce:
There's **only one attribute** in this MetaModel
- Enable manual sorting - **no**
- Group by initial letter(s)
- Grouping length - **1**
- Grouping attribute - MyValue **[text]**
- rendersortattr - MyValue **[text]**
- rendersort - one with **asc** (default), one with **desc**

**Comment by discordier** [comment] 2015-06-30 18:56
@dmolineus This should be disabled right now and therefore the issue should be resolved. Am I right on this one?

**Comment by dmolineus** [comment] 2015-06-30 19:09
Yes, should be fixed by contao-community-alliance/dc-general@fe2f3777c8bebf27184f8afbb15fa1da2b7c95e2 and 772710bb141369f65fa3e850aea428861040007f.

**Comment by discordier** [comment] 2015-06-30 20:16
@cboelter plz test and confirm. Marked as testing so @MiniModel can close it.

**Comment by MiniModel** [comment] 2015-07-03 21:01
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@cboelter could you please have a final look at this and tell if your issue has been resolved?

**Closed by MiniModel** 2015-07-03 21:01 UTC
Labels: backend, bug, testing

**Comment by asaage** [comment] 2015-08-14 12:53
with _Grouping type: Do not group_ the sorting of basic attributes (text,numeric...) works fine but with grouping enabled the ```rendersortattr``` does not seem to be taken into account.

**Comment by dmolineus** [comment] 2015-08-17 09:50
> with Grouping type: Do not group the sorting of basic attributes (text,numeric...) works fine but with grouping enabled the rendersortattr does not seem to be taken into account.

This is a known limitation of MetaModels. It only supports sorting by 1 column. So then using grouping there is currently no way to sort by another column as well.

**Comment by asaage** [comment] 2015-08-17 10:18
Ohh too bad - At least the rendersortattr select field should disapear then.
Is there any chance to have that in Milestone 2.0.0?
Will that be a feature for the future?
