### ISSUE TITLE
Backend integration breaks with syncCto

### ISSUE THREAD

**Issue by richardhj** [MetaModels/core#1012] opened 2016-05-19 16:29 UTC
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | >=5.3; <=5.6         |                                  |
| Contao version:                     | 3.5.12         |                                  |
| MetaModels version:                 | 2.0.0        |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       | bundle-all         |                                  |

## Issue description

The backend integration of MetaModels breaks with the installation of the extension syncCto. The following error message will be shown and the backend execution is stopped due an uncaught exception. After I disabled the Exception, I was able to see that all backend integration settings are unable (see screenshot) and the error disappears without the MetaModel being integrated to the backend. Although the error is caused by the installation of syncCto, I think something is wrong with MetaModels, because - as you can see - only MetaModels methods are seen in the error message.

### Error message
```

Fatal error: Uncaught exception RuntimeException with message Condition of type conditionpropertyvalueis could not be transformed to an instance. thrown in composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php on line 293
#0 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php(322): MetaModels\BackendIntegration\InputScreen\InputScreen->transformCondition(Array)
#1 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/InputScreen/InputScreen.php(113): MetaModels\BackendIntegration\InputScreen\InputScreen->transformConditions(Array)
#2 composer/vendor/metamodels/core/src/MetaModels/Helper/ViewCombinations.php(546): MetaModels\BackendIntegration\InputScreen\InputScreen->__construct(Object(MetaModels\MetaModelsServiceContainer), Array, Array, Array, Array)
#3 composer/vendor/metamodels/core/src/MetaModels/Helper/ViewCombinations.php(609): MetaModels\Helper\ViewCombinations->buildInputScreen('mm_ferienpass')
#4 composer/vendor/metamodels/core/src/MetaModels/Helper/ViewCombinations.php(622): MetaModels\Helper\ViewCombinations->getInputScreenDetails('mm_ferienpass')
#5 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/BackendModuleBuilder.php(304): MetaModels\Helper\ViewCombinations->getStandaloneInputScreens()
#6 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/BackendModuleBuilder.php(76): MetaModels\BackendIntegration\BackendModuleBuilder->resolve()
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Boot.php(115): MetaModels\BackendIntegration\BackendModuleBuilder->__construct(Object(MetaModels\MetaModelsServiceContainer), Object(MetaModels\BackendIntegration\ViewCombinations))
#8 system/modules/metamodels/config/event_listeners.php(65): MetaModels\BackendIntegration\Boot->perform(Object(MetaModels\Events\MetaModelsBootEvent))
#9 [internal function]: ContaoCommunityAlliance\Contao\EventDispatcher\EventDispatcherInitializer->{closure}(Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Object(Closure), Object(MetaModels\Events\MetaModelsBootEvent), 'metamodels.boot...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#12 composer/vendor/metamodels/core/src/MetaModels/Helper/SubSystemBoot.php(128): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.boot...', Object(MetaModels\Events\MetaModelsBootEvent))
#13 system/modules/metamodels/config/config.php(259): MetaModels\Helper\SubSystemBoot->boot(Object(Pimple))
#14 [internal function]: Contao\Config->{closure}(Object(Pimple))
#15 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(116): call_user_func(Object(Closure), Object(Pimple))
#16 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(449): DependencyInjection\Container\ContainerInitializer->callHooks(Object(Pimple))
#17 system/initialize.php(243): DependencyInjection\Container\ContainerInitializer->init()
#18 contao/main.php(16): require('/var/www/ferien...')
#19 {main}
```

## Steps to reproduce

1. All packages are updated via composer, so we can make sure that the error is not caused by a MetaModels update
2. require menatwork/synccto 3.2 (stable 3.0. causes the error too)
3. the error posted below occurs
4. Removing syncCto will vanish the problems too

## Screenshots
![bildschirmfoto 2016-05-19 um 18 15 16](https://cloud.githubusercontent.com/assets/1284725/15401282/171a587c-1def-11e6-86af-c47ecea67b7d.png)
This select does not have any options. Saving this empty select (means, that the MetaModel will not be integrated in the backend) lets the error message disappear.

**Comment by zonky2** [comment] 2016-05-19 16:36
Hi @richardhj - do you have activate any view conditions aka Sub-Palettes?

**Comment by richardhj** [comment] 2016-05-19 17:03
Yes, I defined a ```conditionpropertyvalueis``` for one ```attribute_numeric```. It could be the one mentioned in the error.
The error occurs on every page in the back end and not only in the MetaModels list view.

**Comment by zonky2** [comment] 2016-05-19 19:26
It`s possible to delete the condition? - you can make this in the database - an check your backend

**Comment by richardhj** [comment] 2016-05-19 20:53
After deleting the view conditions, this error does not occur anymore.
Opening the MetaModel in the back end will lead to a
```
Fatal error: Call to a member function getFactory() on a non-object in composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php on line 214
```
I noticed this error before deleting the view conditions too.

**Comment by zonky2** [comment] 2016-05-20 06:10
you can try to update the DCG to beta35 and MM core to alpha11...

it´s not possible to me to readjust the error - have you more intormations?

**Comment by richardhj** [comment] 2016-05-24 21:54
The problem is that the ```serviceContainer``` will not not be set.
syncCto's event subscriber (https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/src/SyncCto/DcGeneral/Events/Subscriber.php#L38) causes the problems and might handicap the execution of MetaModel's events. The problem is: I'm not familiar with the event dispatcher yet. Might we reference syncCto developers here?

**Comment by zonky2** [comment] 2016-05-25 05:17
may be it´s a good idea to write a referenced issue at syncCto...

**Comment by discordier** [comment] 2016-05-25 11:06
@stefanheimes is developer of syncCto, so he most likely will jump in here.

**Comment by stefanheimes** [comment] 2016-05-30 12:41
I test it with this setup:

- Contao 3.5.12
- current MM 2.0.x release
- Sync to in the current 3.2.0-beta 8 version

_I can't reproduce this error._

You say the https://github.com/menatwork/syncCto/blob/master/system/modules/syncCto/src/SyncCto/DcGeneral/Events/Subscriber.php#L38 makes the trouble, have you check if a special call in the function makes trouble? Can you please test it. Just uncomment all ```self::registerListeners``` and add one by one to test it.

**Comment by discordier** [comment] 2016-05-30 13:12
One thing I noticed, you are still using the non functional `$suffixes` in your calls but not in the listener.
All your listeners are missing the checks if the event is intended for them.

**Comment by richardhj** [comment] 2016-06-01 21:54
I noticed and installed your update, @stefanheimes. Concerning your question: every listener causes.
I'm sorry its not getting concrete, but my project has many dependencies installed which makes it unclear for me. (As I noticed, disabling another extension but enabling syncCto fixes it too.) As I need a productive version of this project these days, I cannot give it enough attention, but I keep it rolling.

**Comment by stefanheimes** [comment] 2016-06-02 19:45
My sysmte:
SyncCto current beta
MetaModles current versions

I have only a warning of the color picker. Everything else is running. I have rewrite and check the events. I have at each function a check if the current event is one for syncCto.

**Comment by stefanheimes** [comment] 2016-06-13 10:14
We have open a ticket for the DCG.

https://github.com/contao-community-alliance/dc-general/issues/279

**Comment by discordier** [comment] 2016-06-14 05:50
@stefanheimes fixed the event handlers in syncCto and created a follow up ticket in dcg.
Closing this here therefore.

**Closed by discordier** 2016-06-14 05:50 UTC
Labels: bug, wrong repository
