### ISSUE TITLE
BE - Checkbox filter not working

### ISSUE THREAD

**Issue by Munsio** [MetaModels/core#764] opened 2015-02-26 11:55 UTC
If i define that a checkbox is filterable in the backend list, the filter process is not working for non-active filtering cause non-active is represented by an empty value and filtering for an empty value doesn't work so it is not possible i.e. to filter for non published items

**Comment by cyberlussi** [comment] 2015-08-06 11:26
Confirmed the issue ... unchecked checkbox is not filterable. Indeed for checkbox attributes it would be benificial to use "yes/no" or similar localized instead "1" (and the missing "0"). Especially for checkbox attribute which published entries this makes absolute sence!

![bildschirmfoto 2015-08-06 um 13 20 32](https://cloud.githubusercontent.com/assets/4976687/9110493/6558b95e-3c3e-11e5-9dff-90794ab90202.png)

**Comment by discordier** [comment] 2015-08-12 17:59
Even if we change the behaviour in `getFilterOptions()` to always return
```php
        return array(
            '0' => $GLOBALS['TL_LANG']['MSC']['metamodelattribute_checkbox']['value_0'],
            '1' => $GLOBALS['TL_LANG']['MSC']['metamodelattribute_checkbox']['value_1']
        );
```
in the backend, we have the problem that dcg does not handle empty values ('', 0) properly yet due to the Contao Input class.

**Comment by xantippe** [comment] 2016-01-02 13:11
siehe auch #711

**Comment by xantippe** [comment] 2016-01-13 06:40
mit https://github.com/contao-community-alliance/dc-general/tree/hotfix-unique noch keine Änderung...

**Comment by zonky2** [comment] 2016-12-15 07:03
fixed with https://github.com/MetaModels/attribute_checkbox/commit/2a2e621fa77e9e35bdb63cf0ac31fbcbc3e91809

**Closed by zonky2** 2016-12-15 07:03 UTC
Labels: backend, bug, DC_General
