### ISSUE TITLE
Recoverable error: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event

### ISSUE THREAD

**Issue by Hauge** [MetaModels/core#836] opened 2015-07-13 07:27 UTC
System: Contao 3.4.4
nightly:
```
Name                                             Version              Last modification
=========================================================================================
http://c-c-a.org/
contao-community-alliance/dc-general             dev-develop @ e432a9 2015-07-08 19:03:39
contao-community-alliance/dependency-container   dev-develop @ 5f35ec 2015-07-07 21:25:05
contao-community-alliance/event-dispatcher       dev-develop @ d2da54 2014-11-28 14:49:59
contao-community-alliance/events-contao-bindings dev-master @ 18772d  2015-07-11 09:31:43
contao-community-alliance/translator             dev-master @ 70f446  2015-07-01 15:29:54
-----------------------------------------------------------------------------------------

http://bit3.de
contao-community-alliance/meta-palettes          dev-develop @ 922eb3 2015-01-26 17:45:44
-----------------------------------------------------------------------------------------

https://www.cyberspectrum.de
discordier/justtextwidgets                       0.5.4                2014-02-05 22:52:54
-----------------------------------------------------------------------------------------

http://www.doctrine-project.org
doctrine/cache                                   dev-master @ e7b77e  2015-06-29 15:03:18
-----------------------------------------------------------------------------------------

http://leafo.net/scssphp/
leafo/scssphp                                    v0.1.7               2015-07-02 01:33:11
-----------------------------------------------------------------------------------------

http://www.leo-unglaub.net
leounglaub/contao-simple-ajax                    1.0.2                2014-02-07 22:35:55
-----------------------------------------------------------------------------------------

http://www.men-at-work.de
menatwork/contao-multicolumnwizard               dev-dev @ 875720     2015-05-18 09:39:00
-----------------------------------------------------------------------------------------

http://now.metamodel.me/
metamodels/attribute_alias                       dev-master @ 39da09  2015-07-11 00:15:53
metamodels/attribute_checkbox                    dev-master @ a4c575  2015-07-11 06:00:49
metamodels/attribute_combinedvalues              dev-master @ 6c2b4e  2015-07-11 00:20:19
metamodels/attribute_country                     dev-master @ f5aab4  2015-07-11 00:20:56
metamodels/attribute_decimal                     dev-master @ 9bf9cf  2015-07-11 00:21:48
metamodels/attribute_file                        dev-tng @ 6b5842     2015-07-06 17:39:25
metamodels/attribute_langcode                    dev-master @ 49b6db  2015-07-11 00:22:34
metamodels/attribute_longtext                    dev-master @ 19a66b  2015-07-11 05:52:14
metamodels/attribute_numeric                     dev-master @ 7de2be  2015-07-11 00:39:31
metamodels/attribute_rating                      dev-master @ 1c525a  2015-07-11 06:03:09
metamodels/attribute_select                      dev-master @ 9f1151  2015-07-11 06:12:45
metamodels/attribute_tabletext                   dev-master @ e8ce98  2015-07-11 01:07:52
metamodels/attribute_tags                        dev-master @ 4be245  2015-07-11 06:01:35
metamodels/attribute_text                        dev-master @ ddab6c  2015-07-11 01:24:14
metamodels/attribute_timestamp                   dev-master @ 198665  2015-07-11 02:17:11
metamodels/attribute_translatedalias             dev-master @ fd3f28  2015-07-11 01:41:27
metamodels/attribute_translatedcheckbox          dev-master @ 63bfd0  2015-07-11 06:03:30
metamodels/attribute_translatedcombinedvalues    dev-master @ 9a6186  2015-07-11 02:00:38
metamodels/attribute_translatedfile              dev-master @ 02133c  2015-07-11 02:08:25
metamodels/attribute_translatedlongtext          dev-master @ 3f103e  2015-07-11 02:22:38
metamodels/attribute_translatedselect            dev-tng @ 34d102     2015-07-09 20:25:23
metamodels/attribute_translatedtabletext         dev-master @ f602ca  2015-07-11 10:56:19
metamodels/attribute_translatedtags              dev-master @ 1e2765  2015-07-11 02:41:54
metamodels/attribute_translatedtext              dev-master @ a69c0b  2015-07-11 02:52:04
metamodels/attribute_url                         dev-master @ 9da51a  2015-07-11 03:12:36
metamodels/bundle_all                            dev-master @ f58927  2013-10-01 20:03:31
metamodels/bundle_attributes                     dev-master @ 058e26  2014-02-03 14:19:34
metamodels/bundle_filter                         dev-master @ 45d9cf  2013-05-03 07:16:44
metamodels/bundle_nontranslated                  dev-master @ 5f2b3f  2014-02-17 14:37:26
metamodels/bundle_translated                     dev-master @ 4bc0c1  2014-02-17 14:34:39
metamodels/core                                  dev-tng @ cc6c80     2015-07-11 07:47:58
metamodels/filter_checkbox                       dev-master @ 448ca6  2015-07-11 03:21:41
metamodels/filter_fromto                         dev-master @ 91fcdd  2015-07-11 06:02:21
metamodels/filter_range                          dev-master @ d6015e  2015-07-11 06:02:28
metamodels/filter_select                         dev-master @ 29a063  2015-07-11 05:27:05
metamodels/filter_tags                           dev-master @ 45a13e  2015-07-11 05:36:07
metamodels/filter_text                           dev-master @ 6b6322  2015-07-11 05:50:19
-----------------------------------------------------------------------------------------

https://michelf.ca/projects/php-markdown/
michelf/php-markdown                             1.5.0                2015-03-01 12:03:08
-----------------------------------------------------------------------------------------

http://lessphp.gpeasy.com
oyejorge/less.php                                1.7.x-dev @ 8f77f1   2014-03-04 18:49:54
-----------------------------------------------------------------------------------------

http://pimple.sensiolabs.org
pimple/pimple                                    1.1.x-dev @ bc2fc1   2014-04-20 07:24:09
-----------------------------------------------------------------------------------------

http://simplepie.org/
simplepie/simplepie                              1.3.1                2012-10-30 17:54:03
-----------------------------------------------------------------------------------------

http://swiftmailer.org
swiftmailer/swiftmailer                          5.x-dev @ 0a6e90     2015-06-28 17:20:48
-----------------------------------------------------------------------------------------

https://symfony.com
symfony/event-dispatcher                         2.8.x-dev @ d72468   2015-06-24 15:32:32
symfony/expression-language                      2.8.x-dev @ eccfd6   2015-05-12 15:16:46
-----------------------------------------------------------------------------------------

http://www.tcpdf.org/
tecnick.com/tcpdf                                6.2.9                2015-06-18 09:12:38
-----------------------------------------------------------------------------------------

https://github.com/true/php-punycode
true/punycode                                    1.1.0                2015-03-12 16:49:35
-----------------------------------------------------------------------------------------

other
contao-community-alliance/url-builder            dev-develop @ 5f8997 2014-09-20 03:38:06
contao-components/compass                        0.12.2               2014-11-18 08:30:16
phpspec/php-diff                                 v1.0.2               2013-11-01 13:02:21


```
Fehler beim Click auf das Metamodel:
```

Recoverable error: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event, instance of MetaModels\Events\ParseItemEvent given, called in /home/www/bb-waldeck-2015-07-09/system/modules/metamodels/classes/src/MetaModels/Item.php on line 390 and defined in system/modules/symfony-event-dispatcher/classes/EventDispatcher.php on line 40

#0 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(40): __error(4096, 'Argument 2 pass...', '/home/www/bb-wa...', 40, Array)
#1 system/modules/metamodels/classes/src/MetaModels/Item.php(390): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('metamodels.pars...', Object(MetaModels\Events\ParseItemEvent))
#2 system/modules/metamodels/classes/src/MetaModels/DcGeneral/Events/MetaModel/RenderItem.php(105): MetaModels\Item->parseValue('html5', Object(MetaModels\Render\Setting\Collection))
#3 [internal function]: MetaModels\DcGeneral\Events\MetaModel\RenderItem::render(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FormatModelLabelSubscriber.php(87): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber->handleFormatModelLabel(Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#10 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(253): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(317): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->parseModel(Object(MetaModels\DcGeneral\Data\Model), 'mm_tagespost_tr...')
#12 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(474): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->generateTreeView(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'tree_xtnd')
#13 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(582): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->viewTree(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#15 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(145): call_user_func_array(Array, Array)
#16 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#17 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(168): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#18 system/modules/symfony-event-dispatcher/classes/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#19 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(121): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#20 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#21 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#22 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_ta...')
#23 contao/main.php(20): Contao\BackendMain->run()
#24 {main}


Fatal error: Call to undefined method MetaModels\Events\ParseItemEvent::setDispatcher() in /home/www/der-totale-ordner/system/modules/symfony-event-dispatcher/classes/EventDispatcher.php on line 46
```

**Comment by psren** [comment] 2015-07-13 08:08
Kann ich bestätigen.

```php
// Trigger event to allow other extensions to manipulate the parsed data.
$event = new ParseItemEvent($objSettings, $this, $strOutputFormat, $arrResult);
$this->getMetaModel()->getServiceContainer()->getEventDispatcher()->dispatch(
    MetaModelsEvents::PARSE_ITEM,
    $event
);
```

ParseItemEvent ist einfach kein Symfony\Component\EventDispatcher\Event

**Comment by kikmedia** [comment] 2015-07-13 11:14
confirmed

**Comment by kikmedia** [comment] 2015-07-13 11:15
Probablly related to #835

**Comment by kikmedia** [comment] 2015-07-13 16:04
Thanks a lot, fix works for me. Could you provide a link to your amazon whishlist, please?

**Comment by discordier** [comment] 2015-07-13 16:54
Here you go: http://www.amazon.de/gp/registry/wishlist/3J3K70FYE3EC

**Comment by MiniModel** [comment] 2015-07-16 17:01
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@Hauge could you please have a final look at this and tell if your issue has been resolved?

**Closed by MiniModel** 2015-07-16 17:01 UTC
Labels: bug, frontend, testing

**Comment by Hauge** [comment] 2015-07-17 13:32
Sieht gut aus. Funktioniert.
